# Generated by Django 5.1.5 on 2025-01-20 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodiceAteco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=20)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PianoFormativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('ore_totali', models.FloatField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_avvio', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(blank=True, max_length=50, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('partitaiva', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('cellulare', models.CharField(blank=True, max_length=30, null=True)),
                ('indirizzosl', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('codiceateco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aziende', to='fncapp.codiceateco')),
            ],
        ),
        migrations.CreateModel(
            name='Dipendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(blank=True, max_length=255, null=True)),
                ('sesso', models.CharField(blank=True, max_length=1, null=True)),
                ('datanascita', models.DateField(blank=True, null=True)),
                ('luogonascita', models.CharField(blank=True, max_length=255, null=True)),
                ('provincianascita', models.CharField(blank=True, max_length=255, null=True)),
                ('codicefiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('dataassunzione', models.DateField(blank=True, null=True)),
                ('datacessazione', models.DateField(blank=True, null=True)),
                ('tipocontratto', models.CharField(blank=True, max_length=255, null=True)),
                ('livellocontratto', models.CharField(blank=True, max_length=255, null=True)),
                ('oresettimanali', models.FloatField(blank=True, null=True)),
                ('percparttime', models.FloatField(blank=True, null=True)),
                ('qualifica', models.CharField(blank=True, max_length=255, null=True)),
                ('mansione', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dipendenti', to='fncapp.azienda')),
            ],
        ),
        migrations.CreateModel(
            name='PianoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fncapp.modulo')),
                ('piano_formativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fncapp.pianoformativo')),
            ],
            options={
                'unique_together': {('piano_formativo', 'modulo')},
            },
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='moduli',
            field=models.ManyToManyField(through='fncapp.PianoModulo', to='fncapp.modulo'),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='progetto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piani_formativi', to='fncapp.progetto'),
        ),
        migrations.CreateModel(
            name='ProgettoAzienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capofila', models.BooleanField(default=False)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fncapp.azienda')),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fncapp.progetto')),
            ],
            options={
                'unique_together': {('progetto', 'azienda')},
            },
        ),
        migrations.AddField(
            model_name='progetto',
            name='aziende',
            field=models.ManyToManyField(through='fncapp.ProgettoAzienda', to='fncapp.azienda'),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='fondo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piani_formativi', to='fncapp.tipofondo'),
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore_previste', models.FloatField(blank=True, null=True)),
                ('ore_effettuate', models.FloatField(blank=True, null=True)),
                ('importo_retributivo', models.FloatField(blank=True, null=True)),
                ('importo_contributivo', models.FloatField(blank=True, null=True)),
                ('dipendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fncapp.dipendente')),
                ('piano_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fncapp.pianomodulo')),
            ],
            options={
                'unique_together': {('dipendente', 'piano_modulo')},
            },
        ),
    ]
