# Generated by Django 5.1.5 on 2025-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fncapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='camponote1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='camponote2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='camponote3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
