# Generated by Django 5.1.5 on 2025-01-22 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fncapp', '0002_modulo_camponote1_modulo_camponote2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pianoformativo',
            name='fondo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piani_formativi', to='fncapp.tipofondo'),
        ),
        migrations.AlterField(
            model_name='pianoformativo',
            name='progetto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piani_formativi', to='fncapp.progetto'),
        ),
    ]
