# Generated by Django 5.1.5 on 2025-01-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fncapp', '0004_rappresentantesindacale'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipofondo',
            name='percentuale_dad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tipofondo',
            name='percentuale_fad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pianoformativo',
            name='fondo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piani_formativi', to='fncapp.tipofondo'),
        ),
        migrations.AlterField(
            model_name='pianoformativo',
            name='progetto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='piani_formativi', to='fncapp.progetto'),
            preserve_default=False,
        ),
    ]
