# Generated by Django 5.1.5 on 2025-01-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fncapp', '0005_tipofondo_percentuale_dad_tipofondo_percentuale_fad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pianoformativo',
            old_name='descrizione',
            new_name='denominazione',
        ),
        migrations.RemoveField(
            model_name='pianoformativo',
            name='data_fine',
        ),
        migrations.RemoveField(
            model_name='pianoformativo',
            name='data_inizio',
        ),
        migrations.RemoveField(
            model_name='pianoformativo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pianoformativo',
            name='ore_totali',
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='fabbisogno_formativo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='informazione_comunicazione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='intervento_formativo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='metodologie_didattiche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='processi_innovazione_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='processi_innovazione_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='processo_valorizzazione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianoformativo',
            name='processo_valorizzazione_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
