# Generated by Django 5.1.5 on 2025-01-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fncapp', '0006_rename_descrizione_pianoformativo_denominazione_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulo',
            old_name='camponote1',
            new_name='ada',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='camponote2',
            new_name='denominazione',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='camponote3',
            new_name='entrecomp',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='descrizione',
            new_name='lifecomp',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='nome',
        ),
        migrations.AddField(
            model_name='modulo',
            name='livello_di_standard',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='ore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='processo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='qcer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='risultato_atteso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='sep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='specificita_risultato',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianomodulo',
            name='dad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianomodulo',
            name='fad_asincrona',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianomodulo',
            name='fad_sincrona',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianomodulo',
            name='ore_in_presenza',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pianomodulo',
            name='ore_on_the_job',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
